/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/es2/RC.V:1.1-4.10" *)
module RC(a, b, z, w);
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/es2/RC.V:1.17-1.18" *)
  input a;
  wire a;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/es2/RC.V:1.26-1.27" *)
  input b;
  wire b;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/es2/RC.V:1.46-1.47" *)
  output w;
  wire w;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/es2/RC.V:1.36-1.37" *)
  output z;
  wire z;
  assign z = b & a;
  assign w = b | a;
endmodule
