/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/Full-adder/Full_adder.v:1.1-8.10" *)
module Full_adder(a, b, cin, s, cout);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/Full-adder/Full_adder.v:1.25-1.26" *)
  input a;
  wire a;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/Full-adder/Full_adder.v:1.34-1.35" *)
  input b;
  wire b;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/Full-adder/Full_adder.v:1.43-1.46" *)
  input cin;
  wire cin;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/Full-adder/Full_adder.v:1.65-1.69" *)
  output cout;
  wire cout;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/Full-adder/Full_adder.v:1.55-1.56" *)
  output s;
  wire s;
  assign _0_ = ~(b ^ a);
  assign s = ~(_0_ ^ cin);
  assign _1_ = b & a;
  assign _2_ = cin & ~(_0_);
  assign cout = _2_ | _1_;
endmodule

(* top =  1  *)
(* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/Full-adder/full_adder3.v:1.1-6.10" *)
module full_adder3(a_i, b_i, c_i, s_o, c_o);
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/Full-adder/full_adder3.v:1.32-1.35" *)
  input [2:0] a_i;
  wire [2:0] a_i;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/Full-adder/full_adder3.v:1.49-1.52" *)
  input [2:0] b_i;
  wire [2:0] b_i;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/Full-adder/full_adder3.v:2.10-2.12" *)
  wire c1;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/Full-adder/full_adder3.v:2.14-2.16" *)
  wire c2;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/Full-adder/full_adder3.v:1.60-1.63" *)
  input c_i;
  wire c_i;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/Full-adder/full_adder3.v:1.90-1.93" *)
  output c_o;
  wire c_o;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/Full-adder/full_adder3.v:1.78-1.81" *)
  output [2:0] s_o;
  wire [2:0] s_o;
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/Full-adder/full_adder3.v:3.16-3.52" *)
  Full_adder fa0 (
    .a(a_i[0]),
    .b(b_i[0]),
    .cin(c_i),
    .cout(c1),
    .s(s_o[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/Full-adder/full_adder3.v:4.16-4.51" *)
  Full_adder fa1 (
    .a(a_i[1]),
    .b(b_i[1]),
    .cin(c1),
    .cout(c2),
    .s(s_o[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/Full-adder/full_adder3.v:5.16-5.52" *)
  Full_adder fa2 (
    .a(a_i[2]),
    .b(b_i[2]),
    .cin(c2),
    .cout(c_o),
    .s(s_o[2])
  );
endmodule
