/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/codificatore_di_priorit\37777777703\37777777640/cdp_async.v:1.1-15.10" *)
module cdp_async(in, out, valid);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/codificatore_di_priorit\37777777703\37777777640/cdp_async.v:1.30-1.32" *)
  input [3:0] in;
  wire [3:0] in;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/codificatore_di_priorit\37777777703\37777777640/cdp_async.v:1.51-1.54" *)
  output [1:0] out;
  wire [1:0] out;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/codificatore_di_priorit\37777777703\37777777640/cdp_async.v:1.67-1.72" *)
  output valid;
  wire valid;
  assign _09_ = in[0] & ~(in[1]);
  assign _10_ = in[3] | in[2];
  assign _00_ = _09_ & ~(_10_);
  assign _01_ = _00_ | in[3];
  assign _02_ = in[1] & ~(in[2]);
  assign _03_ = _02_ & ~(in[3]);
  assign _04_ = in[2] & ~(in[3]);
  assign _05_ = _04_ | _03_;
  assign valid = _05_ | _01_;
  assign _06_ = _04_ | _00_;
  assign _07_ = ~(_03_ | _00_);
  assign _08_ = _07_ & ~(_04_);
  assign out[0] = _06_ & ~(_08_);
  assign out[1] = _03_ | _00_;
endmodule
