/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/codificatore_di_priorit\37777777703\37777777640/cdp_sync.v:1.1-15.10" *)
module cdp_sync(in, out, clk, valid);
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/codificatore_di_priorit\37777777703\37777777640/cdp_sync.v:2.5-14.8" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* force_downto = 32'd1 *)
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/codificatore_di_priorit\37777777703\37777777640/cdp_sync.v:0.0-0.0|/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/codificatore_di_priorit\37777777703\37777777640/cdp_sync.v:4.9-13.16|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [1:0] _12_;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/codificatore_di_priorit\37777777703\37777777640/cdp_sync.v:1.66-1.69" *)
  input clk;
  wire clk;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/codificatore_di_priorit\37777777703\37777777640/cdp_sync.v:1.29-1.31" *)
  input [3:0] in;
  wire [3:0] in;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/codificatore_di_priorit\37777777703\37777777640/cdp_sync.v:1.50-1.53" *)
  output [1:0] out;
  reg [1:0] out;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/codificatore_di_priorit\37777777703\37777777640/cdp_sync.v:1.82-1.87" *)
  output valid;
  reg valid;
  assign _10_ = in[0] & ~(in[1]);
  assign _11_ = in[3] | in[2];
  assign _01_ = _10_ & ~(_11_);
  assign _02_ = _01_ | in[3];
  assign _03_ = in[1] & ~(in[2]);
  assign _04_ = _03_ & ~(in[3]);
  assign _05_ = in[2] & ~(in[3]);
  assign _06_ = _05_ | _04_;
  assign _00_ = _06_ | _02_;
  assign _07_ = _05_ | _01_;
  assign _08_ = ~(_04_ | _01_);
  assign _09_ = _08_ & ~(_05_);
  assign _12_[0] = _07_ & ~(_09_);
  assign _12_[1] = _04_ | _01_;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/codificatore_di_priorit\37777777703\37777777640/cdp_sync.v:2.5-14.8" *)
  always @(posedge clk)
    out[0] <= _12_[0];
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/codificatore_di_priorit\37777777703\37777777640/cdp_sync.v:2.5-14.8" *)
  always @(posedge clk)
    out[1] <= _12_[1];
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/codificatore_di_priorit\37777777703\37777777640/cdp_sync.v:2.5-14.8" *)
  always @(posedge clk)
    valid <= _00_;
endmodule
