/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/counter_mod8/counter.v:1.1-15.10" *)
module counter_mod8(clk, reset, enable, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/counter_mod8/counter.v:1.32-1.35" *)
  input clk;
  wire clk;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/counter_mod8/counter.v:1.91-1.96" *)
  output [2:0] count;
  reg [2:0] count;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/counter_mod8/counter.v:1.66-1.72" *)
  input enable;
  wire enable;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/counter_mod8/counter.v:1.48-1.53" *)
  input reset;
  wire reset;
  assign _00_ = count[0] & count[1];
  assign _01_ = ~(_00_ & count[2]);
  assign _02_ = _01_ & ~(count[0]);
  assign _03_ = count[0] ^ count[1];
  assign _04_ = _00_ ^ count[2];
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/counter_mod8/counter.v:2.5-14.8" *)
  always @(posedge clk, posedge reset)
    if (reset) count[0] <= 1'h0;
    else if (enable) count[0] <= _02_;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/counter_mod8/counter.v:2.5-14.8" *)
  always @(posedge clk, posedge reset)
    if (reset) count[1] <= 1'h0;
    else if (enable) count[1] <= _03_;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/counter_mod8/counter.v:2.5-14.8" *)
  always @(posedge clk, posedge reset)
    if (reset) count[2] <= 1'h0;
    else if (enable) count[2] <= _04_;
endmodule
