/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/contatore_up_down/contatore.v:1.1-14.10" *)
module contatore(clk, reset, enable, up_down, data_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* force_downto = 32'd1 *)
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/contatore_up_down/contatore.v:8.27-8.40|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "1 2 3" *)
  wire [3:0] _09_;
  (* force_downto = 32'd1 *)
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/contatore_up_down/contatore.v:8.27-8.40|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _10_;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/contatore_up_down/contatore.v:1.29-1.32" *)
  input clk;
  wire clk;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/contatore_up_down/contatore.v:1.108-1.116" *)
  output [3:0] data_out;
  reg [3:0] data_out;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/contatore_up_down/contatore.v:1.63-1.69" *)
  input enable;
  wire enable;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/contatore_up_down/contatore.v:1.45-1.50" *)
  input reset;
  wire reset;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/contatore_up_down/contatore.v:1.82-1.89" *)
  input up_down;
  wire up_down;
  assign _09_[0] = ~data_out[0];
  assign _00_ = data_out[1] ^ up_down;
  assign _10_[1] = _00_ ^ _09_[0];
  assign _01_ = ~(data_out[2] ^ up_down);
  assign _02_ = up_down | ~(data_out[1]);
  assign _03_ = data_out[0] & ~(_00_);
  assign _04_ = _02_ & ~(_03_);
  assign _10_[2] = ~(_04_ ^ _01_);
  assign _05_ = data_out[3] ^ up_down;
  assign _06_ = up_down | ~(data_out[2]);
  assign _07_ = _01_ & ~(_04_);
  assign _08_ = _06_ & ~(_07_);
  assign _10_[3] = _08_ ^ _05_;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/contatore_up_down/contatore.v:2.5-13.8" *)
  always @(posedge clk, posedge reset)
    if (reset) data_out[0] <= 1'h0;
    else if (enable) data_out[0] <= _09_[0];
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/contatore_up_down/contatore.v:2.5-13.8" *)
  always @(posedge clk, posedge reset)
    if (reset) data_out[1] <= 1'h0;
    else if (enable) data_out[1] <= _10_[1];
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/contatore_up_down/contatore.v:2.5-13.8" *)
  always @(posedge clk, posedge reset)
    if (reset) data_out[2] <= 1'h0;
    else if (enable) data_out[2] <= _10_[2];
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/contatore_up_down/contatore.v:2.5-13.8" *)
  always @(posedge clk, posedge reset)
    if (reset) data_out[3] <= 1'h0;
    else if (enable) data_out[3] <= _10_[3];
  assign _10_[0] = _09_[0];
endmodule
