/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/multiplexer/multiplexer.v:1.1-16.10" *)
module multiplexer(a1, a2, a3, a4, sel, signal);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/multiplexer/multiplexer.v:1.26-1.28" *)
  input a1;
  wire a1;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/multiplexer/multiplexer.v:1.36-1.38" *)
  input a2;
  wire a2;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/multiplexer/multiplexer.v:1.46-1.48" *)
  input a3;
  wire a3;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/multiplexer/multiplexer.v:1.56-1.58" *)
  input a4;
  wire a4;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/multiplexer/multiplexer.v:1.72-1.75" *)
  input [1:0] sel;
  wire [1:0] sel;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/multiplexer/multiplexer.v:1.88-1.94" *)
  output signal;
  wire signal;
  assign _03_ = ~(sel[0] | sel[1]);
  assign _04_ = sel[0] & ~(sel[1]);
  assign _00_ = sel[1] & ~(sel[0]);
  assign _01_ = _00_ ? a3 : a4;
  assign _02_ = _04_ ? a2 : _01_;
  assign signal = _03_ ? a1 : _02_;
endmodule
