/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/es1/CC.V:1.1-5.10" *)
module CC(a, b, y);
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/es1/CC.V:2.11-2.12" *)
  input a;
  wire a;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/es1/CC.V:2.13-2.14" *)
  input b;
  wire b;
  (* src = "/mnt/c/Users/ruozz/OneDrive/Desktop/uni/arch2/VERILOG/primi_es/es1/CC.V:3.12-3.13" *)
  output y;
  wire y;
  assign y = b | a;
endmodule
