/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "comparatore.v:1.1-19.10" *)
module comparatore(A, B, GT, EQ, LT);
  (* src = "comparatore.v:1.26-1.27" *)
  input A;
  wire A;
  (* src = "comparatore.v:1.35-1.36" *)
  input B;
  wire B;
  (* src = "comparatore.v:1.56-1.58" *)
  output EQ;
  wire EQ;
  (* src = "comparatore.v:1.45-1.47" *)
  output GT;
  wire GT;
  (* src = "comparatore.v:1.67-1.69" *)
  output LT;
  wire LT;
  assign EQ = ~(A ^ B);
  assign GT = A & ~(B);
  assign LT = B & ~(A);
endmodule
